steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--no-cache',
    '-t', '$_IMAGE_URI',
    '-f', 'apps/web/Dockerfile',
    '--build-arg', 'NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=$_NEXT_PUBLIC_ALGOLIA_APPLICATION_ID',
    '--build-arg', 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=$_NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY',
    '--build-arg', 'NEXT_PUBLIC_ALGOLIA_AGENT_ID=$_NEXT_PUBLIC_ALGOLIA_AGENT_ID',
    '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
    '--build-arg', 'NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL',
    '.'
  ]
  # Prevent build args from appearing in logs
  secretEnv: []
images:
- '$_IMAGE_URI'

# Cloud Build automatically redacts substitution variables prefixed with _
# from build logs. The NEXT_PUBLIC_* vars are public API keys safe for client-side.
options:
  logging: CLOUD_LOGGING_ONLY
