steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      [
        'build',
        '-t',
        '$_IMAGE_URI',
        '-f',
        'Dockerfile',
        '--build-arg',
        'NEXT_PUBLIC_ALGOLIA_APPLICATION_ID=$_NEXT_PUBLIC_ALGOLIA_APPLICATION_ID',
        '--build-arg',
        'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=$_NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY',
        '--build-arg',
        'NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL',
        '--build-arg',
        'NEXT_PUBLIC_ALGOLIA_SEARCH_INDEX_NAME=$_NEXT_PUBLIC_ALGOLIA_SEARCH_INDEX_NAME',
        '.',
      ]
images:
  - '$_IMAGE_URI'

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
